# Update repo cache and upgrade all packages
#
# Example Usage:
# ansible-playbook update_packages.yaml \
#   -e "target=k8s"
---
- name: Update all packages
  hosts: "{{ target }}"
  become: yes

  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Upgrade all apt packages
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: Check if reboot is required
    register: reboot_required_file
    stat: path=/var/run/reboot-required get_md5=no

  - name: Reboot server
    reboot:
      msg: "Reboot initiated by Ansible due to updates"
      connect_timeout: 5
      reboot_timeout: 300
      pre_reboot_delay: 0
      post_reboot_delay: 30
      test_command: uptime
    when: reboot_required_file.stat.exists
