# Update repo cache and upgrade all packages
#
# Example Usage:
# ansible-playbook update_packages.yaml \
#   -e "target=k8s"
---
- name: Update all packages
  hosts: "{{ target }}"
  become: yes

  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Upgrade all apt packages
    ansible.builtin.apt:
      name: "*"
      state: latest

  - name: Check if reboot is required
    ansible.builtin.stat:
      path: /var/run/reboot-required
      get_checksum: no
    register: reboot_required_file

  - name: Reboot server
    ansible.builtin.reboot:
    when: reboot_required_file.stat.exists == true
